export const ADD_HABIT = 'ADD_HABIT';
export const REMOVE_HABIT = 'REMOVE_HABIT';
export const UPDATE_HABITS = 'UPDATE_HABITS';
export const FETCH_HABITS = 'FETCH_HABITS';
export const FETCH_HABITS_START = 'FETCH_HABITS_START';
export const FETCH_HABITS_SUCCESS = 'FETCH_HABITS_SUCCESS';
export const FETCH_HABITS_ERROR = 'FETCH_HABITS_ERROR';

export const SET_DAY_MODAL = 'SET_DAY_MODAL';
export const CHECK_DAY = 'CHECK_DAY'
export const CLOSE_DAY_MODAL = 'CLOSE_DAY_MODAL';

export const SET_HABIT_MODAL = 'SET_HABIT_MODAL';
export const CLOSE_HABIT_MODAL = 'CLOSE_MODAL';

export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';

export const SIGNUPSUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUPERROR = 'SIGNUP_ERROR';
